/**
 * Webhook Delivery Types - WI-018: Outbound Webhook Delivery System
 *
 * Types for tenant-isolated, durable webhook delivery with HMAC signing and retry logic.
 */

export interface WebhookEndpoint {
  id: string;
  tenantId: string;
  name: string;
  url: string;
  // Do not expose or require plaintext secrets. Use secretRef metadata only.
  secretRef?: string;
  previousSecretRef?: string;
  secretProvider?: string;
  enabled: boolean;
  eventTypes: string[];
  timeoutMs: number;
  maxAttempts: number;
  backoffBaseSeconds: number;
  createdAt: Date;
  updatedAt: Date;
}

export interface WebhookDelivery {
  id: string;
  tenantId: string;
  endpointId: string;
  outboxEventId: string;
  outboxEventType: string;
  correlationId?: string;
  status: WebhookDeliveryStatus;
  attempts: number;
  nextAttemptAt: Date;
  lastError?: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface WebhookAttempt {
  id: string;
  tenantId: string;
  deliveryId: string;
  attemptNumber: number;
  requestTimestamp: Date;
  responseStatus?: number;
  responseBodySnippet?: string;
  durationMs?: number;
  errorMessage?: string;
  createdAt: Date;
}

export type WebhookDeliveryStatus =
  | 'PENDING'
  | 'SENDING'
  | 'DELIVERED'
  | 'FAILED'
  | 'DEAD_LETTER';

export interface WebhookPayload {
  eventType: string;
  eventId: string;
  occurredAt: string;
  payload: any;
  tenantId: string;
  correlationId?: string;
  deliveryId: string;
  attemptNumber: number;
}

export interface WebhookHeaders {
  'X-Webhook-Signature': string;
  'X-Webhook-Timestamp': string;
  'X-Webhook-Event': string;
  'X-Webhook-Delivery-Id': string;
  'X-Tenant-Id': string;
  'X-Correlation-Id'?: string;
  'Content-Type': string;
  'User-Agent': string;
}

export interface WebhookDeliveryResult {
  success: boolean;
  statusCode?: number;
  responseBody?: string;
  durationMs: number;
  error?: string;
}

export interface CreateWebhookEndpointRequest {
  tenantId: string;
  name: string;
  url: string;
  // secret material is never accepted here; it is generated and stored via SecretService
  eventTypes: string[];
  timeoutMs?: number;
  maxAttempts?: number;
  backoffBaseSeconds?: number;
  // secretRef is generated by service and persisted via repository
  secretRef?: string;
  previousSecretRef?: string;
  secretProvider?: string;
}

export interface UpdateWebhookEndpointRequest {
  name?: string;
  url?: string;
  // plaintext secret updates are forbidden; rotation handled via SecretService
  enabled?: boolean;
  eventTypes?: string[];
  timeoutMs?: number;
  maxAttempts?: number;
  backoffBaseSeconds?: number;
  // allow metadata updates only
  secretRef?: string;
  previousSecretRef?: string;
  secretProvider?: string;
  secretUpdatedAt?: Date;
}
