#!/bin/bash

echo "🧪 YOLO Mode Verification Test"
echo "=============================="
echo ""

echo "📋 Checking Continue Configuration:"
echo "   - Config file exists: $([ -f ~/.continue/.continuerc.json ] && echo '✅' || echo '❌')"
echo "   - allowExecute: $(jq -r '.allowExecute' ~/.continue/.continuerc.json 2>/dev/null)"
echo "   - confirmBeforeExecute: $(jq -r '.confirmBeforeExecute' ~/.continue/.continuerc.json 2>/dev/null)"
echo "   - enableYoloMode: $(jq -r '.enableYoloMode' ~/.continue/.continuerc.json 2>/dev/null)"
echo "   - toolApprovalPolicy: $(jq -r '.toolApprovalPolicy' ~/.continue/.continuerc.json 2>/dev/null)"
echo ""

echo "🔄 Testing Ollama Connection:"
echo "   - Daemon status: $(curl -s http://localhost:11434/api/tags >/dev/null && echo '✅ Running' || echo '❌ Not running')"
echo ""

echo "📝 MANUAL VERIFICATION REQUIRED:"
echo "================================"
echo ""
echo "1. Open VS Code and Continue chat"
echo "2. Type this exact message:"
echo "   'Run: echo \"YOLO mode working!\"'"
echo ""
echo "3. Check results:"
echo "   ✅ If you see 'YOLO mode working!' without any approval dialogs = SUCCESS"
echo "   ❌ If you see approval prompts = YOLO mode still broken"
echo ""
echo "4. If broken, try these additional steps:"
echo "   - In VS Code: Cmd+Shift+P → 'Continue: Open Settings'"
echo "   - Set ALL Tool Policies to AUTOMATIC manually"
echo "   - Restart VS Code again"
echo ""

echo "🎯 Expected Outcome:"
echo "==================="
echo "Continue should execute terminal commands instantly"
echo "No 'Allow this action?' popups should appear"
echo "File edits should happen automatically"