#!/bin/bash

echo "🧪 Testing Gemini Model Fix for Thinking Role Error"
echo "==================================================="
echo ""

echo "📋 Current Gemini Model Configuration:"
echo "======================================"
grep -A 10 "Gemini 3 Pro Preview" ~/.continue/config.yaml
echo ""

echo "🔍 What Was Fixed:"
echo "=================="
echo "1. ✅ REMOVED 'edit' and 'apply' roles from Gemini model"
echo "2. ✅ KEPT ONLY 'chat' role to prevent agent mode thinking generation"
echo "3. ✅ Agent mode with edit/apply triggers internal 'thinking' roles"
echo "4. ✅ Gemini API rejects 'thinking' role causing 'Invalid role: thinking' error"
echo ""

echo "🧪 MANUAL TESTING REQUIRED:"
echo "==========================="
echo ""
echo "1. Restart VS Code completely:"
echo "   Cmd+Q → Wait 10 seconds → Reopen VS Code"
echo ""
echo "2. Test Gemini model in Continue:"
echo "   - Select 'Gemini 3 Pro Preview' model"
echo "   - Try a simple chat message: 'Hello, how are you?'"
echo "   - Should work without 'Invalid role: thinking' errors"
echo ""
echo "3. Test Agent Mode (should now be restricted):"
echo "   - Switch to Agent Mode in Continue"
echo "   - Try to use edit/apply features with Gemini"
echo "   - Should either work (if compatible) or gracefully fail without thinking errors"
echo ""

echo "🎯 EXPECTED OUTCOME:"
echo "===================="
echo "✅ Gemini model works in chat mode without thinking role errors"
echo "✅ Agent mode either works or fails gracefully (no API errors)"
echo "✅ Other Ollama models still support full agent mode features"
echo ""

echo "If you still get thinking role errors with Gemini:"
echo "- The model may need to be used in simple chat mode only"
echo "- Consider switching to a different Ollama model for agent features"
echo "- Report the issue to Continue team if it persists"