// Voice Outcome Enums
// All voice interactions must result in one of these enumerated outcomes
// NO DIRECT FSM STATE CHANGES ALLOWED

export enum VoiceOutcome {
  // Successful Contact Outcomes
  CONTACTED_SUCCESSFUL = 'CONTACTED_SUCCESSFUL',
  CONTACTED_UNSUCCESSFUL = 'CONTACTED_UNSUCCESSFUL',

  // Connection Outcomes
  NO_ANSWER = 'NO_ANSWER',
  VOICEMAIL_LEFT = 'VOICEMAIL_LEFT',
  WRONG_NUMBER = 'WRONG_NUMBER',
  CALL_BLOCKED = 'CALL_BLOCKED',

  // Communication Outcomes
  LANGUAGE_BARRIER = 'LANGUAGE_BARRIER',
  TECHNICAL_ISSUE = 'TECHNICAL_ISSUE',

  // Business Outcomes (Informational Only - No Direct State Changes)
  INTEREST_EXPRESSED = 'INTEREST_EXPRESSED',
  OBJECTION_RAISED = 'OBJECTION_RAISED',
  QUESTION_ASKED = 'QUESTION_ASKED',
  INFORMATION_REQUESTED = 'INFORMATION_REQUESTED',
  FOLLOWUP_REQUESTED = 'FOLLOWUP_REQUESTED',
  NOT_INTERESTED = 'NOT_INTERESTED',

  // Process Outcomes
  CALL_COMPLETED = 'CALL_COMPLETED',
  CALL_TRANSFERRED = 'CALL_TRANSFERRED',
  CALL_DROPPED = 'CALL_DROPPED',
  CALLBACK_REQUESTED = 'CALLBACK_REQUESTED',
}

// Blocked Outcomes - These are NEVER allowed
export const BLOCKED_OUTCOMES = [
  'DIRECT_STATE_CHANGE',
  'MANUAL_QUALIFICATION',
  'AUTO_CLOSE_WON',
  'AUTO_CLOSE_LOST',
  'BYPASS_APPROVAL',
] as const;

// Voice Mode Enums
export enum VoiceMode {
  AUTONOMOUS = 'AUTONOMOUS', // AI-only, script-locked, enum outcomes
  ASSISTED = 'ASSISTED', // Human speaks, AI guides, checklist enforced
  HUMAN_ONLY = 'HUMAN_ONLY', // Human speaks freely, still must log outcomes
}

// Actor Types
export enum VoiceActor {
  AI = 'AI',
  HUMAN = 'HUMAN',
  HYBRID = 'HYBRID', // Future: AI + Human collaboration
}

// Call Direction
export enum CallDirection {
  OUTBOUND = 'OUTBOUND',
  INBOUND = 'INBOUND',
}

// Voice Quality Metrics
export enum QualityMetric {
  CONFIDENCE_SCORE = 'CONFIDENCE_SCORE',
  SPEECH_CLARITY = 'SPEECH_CLARITY',
  BACKGROUND_NOISE = 'BACKGROUND_NOISE',
  LATENCY = 'LATENCY',
  SCRIPT_ADHERENCE = 'SCRIPT_ADHERENCE',
}

// Script Types
export enum ScriptType {
  QUALIFICATION = 'QUALIFICATION',
  VALUE_PROPOSITION = 'VALUE_PROPOSITION',
  OBJECTION_HANDLING = 'OBJECTION_HANDLING',
  NEEDS_ANALYSIS = 'NEEDS_ANALYSIS',
  BUDGET_DISCOVERY = 'BUDGET_DISCOVERY',
  DECISION_MAKER_IDENTIFICATION = 'DECISION_MAKER_IDENTIFICATION',
  PROPOSAL_FOLLOWUP = 'PROPOSAL_FOLLOWUP',
  NEGOTIATION = 'NEGOTIATION',
  COMMITMENT_CONFIRMATION = 'COMMITMENT_CONFIRMATION',
  NEXT_STEPS = 'NEXT_STEPS',
  ONBOARDING_WELCOME = 'ONBOARDING_WELCOME',
  GRACIOUS_LOSS = 'GRACIOUS_LOSS',
  REFERRAL_REQUEST = 'REFERRAL_REQUEST',
  ACKNOWLEDGMENT = 'ACKNOWLEDGMENT',
  OUTCOME_COLLECTION = 'OUTCOME_COLLECTION',
}

// Compliance Flags
export enum ComplianceFlag {
  RECORDING_REQUIRED = 'RECORDING_REQUIRED',
  PII_MASKING_ENABLED = 'PII_MASKING_ENABLED',
  AUDIT_RETENTION = 'AUDIT_RETENTION',
  SUPERVISOR_OVERRIDE = 'SUPERVISOR_OVERRIDE',
}
